{% set name = "radis" %}
{% set version = "0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radis-{{ version }}.tar.gz
  sha256: 82320a54dd1d133672ef229f4346f5b3d0a6ff5f24a017efa470d890f40ddb2e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    # build time dependencies
    - python
    - cython
    - numpy
    - pip
  run:
    # runtime dependencies
    - python
    - astropy-base
    - astroquery >=0.3.9
    - beautifulsoup4
    - configparser
    - cython
    - lxml
    - matplotlib-base
    - habanero
    - h5py
    - hjson-py
    - ipython >=7.0.0
    - joblib
    - json_tricks >=3.15.0
    - pandas >=1.0.5
    - plotly >=2.5.1
    - progressbar2
    - numba
    - mpldatacursor
    - peakutils
    - termcolor
    - pytables
    - pytest
    - psutil
    - seaborn
    - scipy >=1.4.0
    - lmfit
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - radis

about:
  home: https://github.com/radis/radis
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A fast line-by-line code for high-resolution infrared molecular spectra
  doc_url: https://radis.readthedocs.io/en/latest/
  dev_url: https://github.com/radis/radis

extra:
  recipe-maintainers:
    - arunavabasucom
    - erwanp
